src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>First_Action_Date__c</fullName>
        <description>The date this contact first took action.</description>
        <inlineHelpText>The date this contact first took action.</inlineHelpText>
        <label>First Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Action_Date__c</fullName>
        <description>The date this contact last took action.</description>
        <inlineHelpText>The data this contact last took action.</inlineHelpText>
        <label>Last Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Actions_30_Days__c</fullName>
        <description>Total number of actions last 30 days.</description>
        <inlineHelpText>Total number of actions taken in the last 30 days.</inlineHelpText>
        <label>Total Actions (30 Days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Message_Actions__c</fullName>
        <description>The total number of message actions taken.</description>
        <inlineHelpText>The total number of message actions taken by this contact.</inlineHelpText>
        <label>Total Message Actions</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Petitions_Signed__c</fullName>
        <description>Total number of petitions signed.</description>
        <inlineHelpText>Total number of petitions signed.</inlineHelpText>
        <label>Total Petitions Signed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Social_Actions__c</fullName>
        <description>The total number of social actions taken.</description>
        <inlineHelpText>The total number of social actions taken by this contact.</inlineHelpText>
        <label>Total Social Actions</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P2P_Personal_Campaign__c.object
<CustomObject>
    <description>Personal campaigns are campaigns created by end users on behalf of an organization</description>
    <fields>
        <fullName>First_Action_Date__c</fullName>
        <description>The date this campaign first had an action taken.</description>
        <inlineHelpText>The date this campaign first had an action taken.</inlineHelpText>
        <label>First Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Action_Date__c</fullName>
        <description>The date this campaign last had an action taken.</description>
        <inlineHelpText>The date this campaign last had an action taken.</inlineHelpText>
        <label>Last Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P2P_Campaigner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>P2P Personal Campaigns (Contact)</relationshipLabel>
        <relationshipName>P2P_Personal_Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Message_Actions__c</fullName>
        <description>The total number of message actions taken.</description>
        <inlineHelpText>The total number of message actions taken by this contact.</inlineHelpText>
        <label>Total Message Actions</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Petitions_Signed__c</fullName>
        <description>Total number of petitions signed.</description>
        <inlineHelpText>Total number of petitions signed.</inlineHelpText>
        <label>Total Petitions Signed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Social_Actions__c</fullName>
        <description>The total number of social actions taken.</description>
        <inlineHelpText>The total number of social actions taken by this contact.</inlineHelpText>
        <label>Total Social Actions</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>P2P Personal Campaign</label>
    <nameField>
        <label>P2P Personal Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P2P Personal Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/sb_action__c.object
<CustomObject>
    <description>Springboard Advocacy Object for all actions.</description>
    <fields>
        <fullName>Actions_Taken__c</fullName>
        <description>The total number of contacts who have successfully taken this action. (CONFIRM)</description>
        <inlineHelpText>The total number of contacts who have successfully taken this action. (CONFIRM)</inlineHelpText>
        <label>Actions Taken</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Created__c</fullName>
        <description>Create date of the action</description>
        <inlineHelpText>Create date of the action</inlineHelpText>
        <label>Date Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Action_Date__c</fullName>
        <description>Date of the first action taken.</description>
        <inlineHelpText>Date of the first action taken.</inlineHelpText>
        <label>First Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Action_Date__c</fullName>
        <description>Date of the last action taken.</description>
        <inlineHelpText>Date of the last action taken.</inlineHelpText>
        <label>Last Action Date</label>
        <type>DateTime</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/sb_Actions_Taken__c.object
<CustomObject>
    <description>A list of which actions have been taken by which contacts.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <description>Type of action</description>
        <inlineHelpText>Type of action</inlineHelpText>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Message Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Petition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Action</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <description>Springboard actions</description>
        <inlineHelpText>A Springboard action.</inlineHelpText>
        <label>Action</label>
        <referenceTo>sb_action__c</referenceTo>
        <relationshipLabel>Actions Taken</relationshipLabel>
        <relationshipName>Actions_Taken</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact who has taken action.</description>
        <inlineHelpText>This person has taken this action.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Actions Taken</relationshipLabel>
        <relationshipName>Actions_Taken</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Action__c</fullName>
        <description>Date the action was taken.</description>
        <inlineHelpText>Date the action was taken.</inlineHelpText>
        <label>Date of Action</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>P2P_Personal_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The peer to peer personal campaign from which the action originated.</description>
        <label>P2P Personal Campaign</label>
        <referenceTo>P2P_Personal_Campaign__c</referenceTo>
        <relationshipLabel>Actions Taken</relationshipLabel>
        <relationshipName>Actions_Taken</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Actions Taken</label>
    <nameField>
        <label>Actions Taken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Taken</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActionsTakenTriggerHandler_TESTS.cls
@isTest
public class ActionsTakenTriggerHandler_TESTS {
    
    @testSetup
	private static void SetupTestData() {
    	Contact contact = new Contact();
        contact.FirstName = 'John';
        contact.LastName = 'Doe';
        contact.email = 'ActionsTakenTriggerHandler_TESTS@example.com';
        insert contact;
        
        P2P_Personal_Campaign__c personalCampaign = new P2P_Personal_Campaign__c();
        personalCampaign.Name = 'John Doe\'s Personal Campaign';
        personalCampaign.P2P_Campaigner__c = contact.Id;
        insert personalCampaign;
	}
    
	@isTest
    private static void ActionsTakenTriggerTESTS() {
        Test.startTest();
        Contact contact = [SELECT Id FROM Contact WHERE Email='ActionsTakenTriggerHandler_TESTS@example.com'];
        P2P_Personal_Campaign__c personalCampaign = [SELECT Id FROM P2P_Personal_Campaign__c WHERE P2P_Campaigner__c=:contact.Id];
        
        sb_action__c  action = new sb_action__c ();
        action.Name = 'Test Action';
        action.Date_Created__c = Date.today();
        insert action;
        
        sb_Actions_Taken__c actionTaken = new sb_Actions_Taken__c();
        actionTaken.Action__c = action.Id;
        actionTaken.Name = 'Action 1';
        actionTaken.Contact__c = contact.Id;
        actionTaken.Action_Type__c = 'Petition';
        insert actionTaken;
        
        sb_Actions_Taken__c socialActionTaken = new sb_Actions_Taken__c();
        socialActionTaken.Action__c = action.Id;
        socialActionTaken.Name = 'Action 2';
        socialActionTaken.Contact__c = contact.Id;
        socialActionTaken.P2P_Personal_Campaign__c = personalCampaign.Id;
        socialActionTaken.Action_Type__c = 'Social Action';
        insert socialActionTaken;
        
        sb_Actions_Taken__c petitionsSigned = new sb_Actions_Taken__c();
        petitionsSigned.Action__c = action.Id;
        petitionsSigned.Name = 'Action 3';
        petitionsSigned.Contact__c = contact.Id;
        petitionsSigned.P2P_Personal_Campaign__c = personalCampaign.Id;
        petitionsSigned.Action_Type__c = 'Petition';
        insert petitionsSigned;

		Test.stopTest();
        
        contact = [SELECT First_Action_Date__c, Last_Action_Date__c, Total_Message_Actions__c, Total_Social_Actions__c, Total_Petitions_Signed__c, Total_Actions_30_Days__c FROM Contact WHERE Id = :contact.Id];
        System.assertEquals(3, contact.Total_Actions_30_Days__c);
        System.assertEquals(2, contact.Total_Petitions_Signed__c);
        System.assertEquals(1, contact.Total_Social_Actions__c);
        System.assertEquals(Date.today(), contact.First_Action_Date__c);
        System.assertEquals(Date.today(), contact.Last_Action_Date__c);

        action = [SELECT Actions_Taken__c, First_Action_Date__c, Last_Action_Date__c FROM sb_action__c WHERE Id = :action.Id];
        System.assertEquals(3, action.Actions_Taken__c);
        System.assertEquals(Date.today(), action.First_Action_Date__c);
        System.assertEquals(Date.today(), action.Last_Action_Date__c);
 
        personalCampaign = [SELECT First_Action_Date__c, Last_Action_Date__c, Total_Message_Actions__c, Total_Social_Actions__c, Total_Petitions_Signed__c FROM P2P_Personal_Campaign__c WHERE P2P_Campaigner__c=:contact.Id];
        System.assertEquals(1, personalCampaign.Total_Petitions_Signed__c);
        System.assertEquals(1, personalCampaign.Total_Social_Actions__c);
        System.assertEquals(Date.today(), personalCampaign.First_Action_Date__c);
        System.assertEquals(Date.today(), personalCampaign.Last_Action_Date__c);
 
    }
    
	@isTest
    private static void ActionsTakenPeriodicRollupTests() {
        Contact contact = [SELECT Id FROM Contact WHERE Email='ActionsTakenTriggerHandler_TESTS@example.com'];

        Test.startTest();
        
        sb_action__c  action = new sb_action__c ();
        action.Name = 'Test Action';
        action.Date_Created__c = Date.today();
        insert action;
        
        sb_Actions_Taken__c actionTaken = new sb_Actions_Taken__c();
        actionTaken.Action__c = action.Id;
        actionTaken.Name = 'Action 1';
        actionTaken.Contact__c = contact.Id;
        actionTaken.Action_Type__c = 'Petition';
        actionTaken.Date_of_Action__c = Date.today().addDays(-4);
        insert actionTaken;
        
        sb_Actions_Taken__c socialActionTaken = new sb_Actions_Taken__c();
        socialActionTaken.Action__c = action.Id;
        socialActionTaken.Name = 'Action 2';
        socialActionTaken.Contact__c = contact.Id;
        socialActionTaken.Action_Type__c = 'Social Action';
        socialActionTaken.Date_of_Action__c = Date.today().addDays(-40);
        insert socialActionTaken;
        
        // Run a mock scheduled batch.
		ActionsTakenPeriodicRollupScheduler scheduler = new ActionsTakenPeriodicRollupScheduler();
		SchedulableContext context;
		scheduler.execute(context);
        
		Test.stopTest();
        
        // Only the action within 30 days should be counted after the batch has run.
        contact = [SELECT Total_Actions_30_Days__c FROM Contact WHERE Id = :contact.Id];
        System.assertEquals(1, contact.Total_Actions_30_Days__c);
    }
}