src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_Actions_30_Days__c</fullName>
        <description>Total number of actions last 30 days.</description>
        <inlineHelpText>Total number of actions taken in the last 30 days.</inlineHelpText>
        <label>Total Actions (30 Days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sb_Actions_Taken__c.object
<CustomObject>
    <description>A list of which actions have been taken by which contacts.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact who has taken action.</description>
        <inlineHelpText>This person has taken this action.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Actions Taken</relationshipLabel>
        <relationshipName>Actions_Taken</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Action__c</fullName>
        <description>Date the action was taken.</description>
        <inlineHelpText>Date the action was taken.</inlineHelpText>
        <label>Date of Action</label>
        <type>DateTime</type>
    </fields>
    <label>Actions Taken</label>
    <nameField>
        <label>Actions Taken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Taken</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActionsTakenPeriodicRollup.cls
global with sharing class ActionsTakenPeriodicRollup implements Database.Batchable<SObject>, Database.Stateful {

	global List<Contact> contacts;
	
	global ActionsTakenPeriodicRollup(List<Contact> contacts) {
		this.contacts = contacts;
	}

    global List<Contact> start(Database.BatchableContext context) {
        return this.contacts;
    }
    
    global void execute(Database.BatchableContext context, List<Contact> scope) {
    	Set<Id> contactIds = new Set<Id>();
		for (Contact contact : scope) {
			contactIds.add(contact.Id);
		}
		Map<Id, AggregateResult> contactActionCounts = new Map<Id, AggregateResult>([
			SELECT Contact__r.Id, COUNT(Id) FROM sb_Actions_Taken__c 
			WHERE Contact__c IN :contactIds AND Date_of_Action__c > :DateTime.now().addDays(-30)
			GROUP BY Contact__r.Id
		]);
		AggregateResult actionCount;
		for (Contact contact : scope) {
			actionCount = contactActionCounts.get(contact.Id);
			contact.Total_Actions_30_Days__c = (actionCount == NULL) ? 0 : Integer.valueOf(actionCount.get('expr0'));
		}
		
		// Save the updated Contacts.
		update scope;
    }
    
    global void finish(Database.BatchableContext context) {
       
    }
}