src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OCDonate_Active_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This points to the contact&apos;s active One Click Donate subscription object.</description>
        <inlineHelpText>This points to the contact&apos;s active One Click Donate subscription object.</inlineHelpText>
        <label>One Click Donate Active Subscription</label>
        <referenceTo>One_Click_Donate_Subscription__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCDonate_CC_Exp_Month__c</fullName>
        <description>Expiration month (number) of the credit card used by the contact&apos;s active One Click Donate subscription.</description>
        <inlineHelpText>Expiration month (number) of the credit card used by the contact&apos;s active One Click Donate subscription.</inlineHelpText>
        <label>One Click Donate CC Exp Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCDonate_CC_Exp_Year__c</fullName>
        <description>Expiration year of the credit card used by the contact&apos;s One Click Donate subscription.</description>
        <inlineHelpText>Expiration year of the credit card used by the contact&apos;s One Click Donate subscription.</inlineHelpText>
        <label>One Click Donate CC Exp Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCDonate_CC_Last_4__c</fullName>
        <description>Last 4 digits of the credit card used by the contact&apos;s active One Click Donate subscription.</description>
        <inlineHelpText>Last 4 digits of the credit card used by the contact&apos;s active One Click Donate subscription.</inlineHelpText>
        <label>One Click Donate CC Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCDonate_CC_Type__c</fullName>
        <description>Type of credit card used by the contact&apos;s active One Click Donate subscription.</description>
        <inlineHelpText>Type of credit card used by the contact&apos;s active One Click Donate subscription.</inlineHelpText>
        <label>One Click Donate CC Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCDonate_Payment_Gateway__c</fullName>
        <description>Payment gateway used by the contact&apos;s active OCD subscription.</description>
        <inlineHelpText>Payment gateway used by the contact&apos;s active OCD subscription.</inlineHelpText>
        <label>One Click Donate Payment Gateway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCDonate_Token_Expiration__c</fullName>
        <description>Date/time at which the current OCD token expires.</description>
        <inlineHelpText>Date/time at which the current OCD token expires.</inlineHelpText>
        <label>One Click Donate Token Expiration</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OCDonate_URL__c</fullName>
        <description>One Click Donate HMAC token.</description>
        <inlineHelpText>Append this token to the site/form URL to facilitate a one-click donation.</inlineHelpText>
        <label>One Click Donate URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/One_Click_Donate_Subscription__c.object
<CustomObject>
    <description>Springboard one click donate information.</description>
    <fields>
        <fullName>CC_Exp_Month__c</fullName>
        <label>CC Exp Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Exp_Year__c</fullName>
        <label>CC Exp Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Last_4__c</fullName>
        <description>The last 4 digits of the credit card used for this one click donate subscription.</description>
        <inlineHelpText>The last 4 digits of the credit card used for this one click donate subscription.</inlineHelpText>
        <label>CC Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Type__c</fullName>
        <label>CC Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>One Click Donate Subscriptions</relationshipLabel>
        <relationshipName>One_Click_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Payment_Method__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Payment Method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <label>Payment Gateway</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>One Click Donate Subscription</label>
    <nameField>
        <label>One Click Donate Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One Click Donate Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SB_OCDonate_Trigger_OCDSubscription.cls
public with sharing class SB_OCDonate_Trigger_OCDSubscription extends SpringboardTriggerHandler {
	
	public override void onAfterInsert() {
		List<Id> contactIds = new List<Id>();
		List<One_Click_Donate_Subscription__c> nonDefaultSubscriptions = new List<One_Click_Donate_Subscription__c>();
	    for (One_Click_Donate_Subscription__c subscription : (One_Click_Donate_Subscription__c[]) Trigger.new) {
	    	contactIds.add(subscription.Contact__c);
	    	if (!subscription.Default_Payment_Method__c) {
				nonDefaultSubscriptions.add(subscription);
			}
	    }
	    Map<Id, Contact> contacts = new Map<Id, Contact>([
	    	SELECT OCDonate_CC_Exp_Month__c, OCDonate_CC_Exp_Year__c, OCDonate_Payment_Gateway__c, 
	    		OCDonate_CC_Last_4__c, OCDonate_CC_Type__c, OCDonate_Active_Subscription__c, 
	    		OCDonate_Token_Expiration__c, OCDonate_URL__c
	    	FROM Contact
	    	WHERE Id IN :contactIds
	    ]);
	    // Blank the opt-outs first.
	    for (One_Click_Donate_Subscription__c subscription : nonDefaultSubscriptions) {
	    	Contact contact = contacts.get(subscription.Contact__c);
	    	if (contact.OCDonate_Active_Subscription__c == subscription.Id) {
		    	contact.OCDonate_Active_Subscription__c = null;
		    	contact.OCDonate_URL__c = null;
		    	contact.OCDonate_Token_Expiration__c = null;
		    	contact.OCDonate_CC_Exp_Month__c = null;
		    	contact.OCDonate_CC_Exp_Year__c = null;
		    	contact.OCDonate_CC_Last_4__c = null;
		    	contact.OCDonate_CC_Type__c = null;
		    	contact.OCDonate_Payment_Gateway__c = null;
	    	}
	    }
	    // Propagate the data from active default subscriptions.
	    for (One_Click_Donate_Subscription__c subscription : (One_Click_Donate_Subscription__c[]) Trigger.new) {
	    	Contact contact = contacts.get(subscription.Contact__c);
	    	if (subscription.Default_Payment_Method__c) {
		    	// Propagate subscription details to contact.
		    	contact.OCDonate_Active_Subscription__c = subscription.Id;
		    	String expMonth = String.valueOf(Integer.valueOf(subscription.CC_Exp_Month__c));  // string representation, no decimals
		    	if (expMonth != null && expMonth.length() > 2) { expMonth = expMonth.substring(expMonth.length() - 2); }  // limit to 2 characters
		    	contact.OCDonate_CC_Exp_Month__c = (expMonth == null) ? '' : expMonth;
		    	String expYear = String.valueOf(Integer.valueOf(subscription.CC_Exp_Year__c));  // string representation, no decimals
		    	if (expYear != null && expYear.length() > 4) { expYear = expYear.substring(expYear.length() - 4); }  // limit to 4 characters
		    	contact.OCDonate_CC_Exp_Year__c = (expYear == null) ? '' : expYear;
		    	contact.OCDonate_CC_Last_4__c = subscription.CC_Last_4__c;
		    	contact.OCDonate_CC_Type__c = subscription.CC_Type__c;
		    	contact.OCDonate_Payment_Gateway__c = subscription.Payment_Gateway__c;
	    	}
	    }
	    // Save the updated contacts.
	    update contacts.values();
	}
	
	public override void onAfterUpdate() {
		this.onAfterInsert();
	}
}