src/objects/Sustainer_Upgrade__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sustainers_Upgrade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Failure_Flag__c</fullName>
        <label>Failure Flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Sustainer Upgrade</label>
    <nameField>
        <label>Sustainer Upgrade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sustainer Upgrades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SB_Sustainers_Trigger_SustainerUpgrade.cls
public with sharing class SB_Sustainers_Trigger_SustainerUpgrade extends SpringboardTriggerHandler {
	
	public override void onAfterInsert() {
	    Map<Id, DateTime> contactIdToLatestTimestamp = new Map<Id, DateTime>();
	    Map<Id, Boolean> contactIdToLatestSuccess = new Map<Id, Boolean>();
	    for (Sustainer_Upgrade__c upgrade : (Sustainer_Upgrade__c[]) Trigger.new) {
	        if (upgrade.Contact__c != NULL && (contactIdToLatestTimestamp.get(upgrade.Contact__c) == NULL 
	            || contactIdToLatestTimestamp.get(upgrade.Contact__c) < upgrade.Timestamp__c)
	        ) {
	            contactIdToLatestTimestamp.put(upgrade.Contact__c, upgrade.Timestamp__c);
	            contactIdToLatestSuccess.put(upgrade.Contact__c, String.isBlank(upgrade.Failure_Flag__c));
	        }
	    }
	    if (contactIdToLatestTimestamp.size() > 0) {
	        // Query and update the relevant Contact records.
	        List<Contact> contacts = [
	            SELECT Last_Sustainer_Upgrade_Date__c, Last_Sustainer_Upgrade_Successful__c
	            FROM Contact WHERE Id IN :contactIdToLatestTimestamp.keySet() 
	        ];
	        for (Contact contact : contacts) {
	            if (contact.Last_Sustainer_Upgrade_Date__c == null 
	                || contactIdToLatestTimestamp.get(contact.Id) > contact.Last_Sustainer_Upgrade_Date__c
	            ) {
	                contact.Last_Sustainer_Upgrade_Date__c = contactIdToLatestTimestamp.get(contact.Id);
	                contact.Last_Sustainer_Upgrade_Successful__c = contactIdToLatestSuccess.get(contact.Id);
	            }
	        }
	        update contacts;
	    }
	}
}